#!/bin/sh
#
# Alarm warning ranges only.

IAM=$(basename $0)

if [ ! -d tests/outputs ]; then
	mkdir tests/outputs
fi

dhcpd-pools -L 11 --warning=50 -c $top_srcdir/tests/confs/complete \
	    -l $top_srcdir/tests/leases/complete -o tests/outputs/$IAM
echo $? >> tests/outputs/$IAM

diff -u $top_srcdir/tests/expected/$IAM tests/outputs/$IAM
exit $?
