#!/bin/sh
#
# Minimal regression test suite.

IAM=$(basename $0)

if [ ! -d tests/outputs ]; then
	mkdir tests/outputs
fi

dhcpd-pools --warning 1 --critical 101 --min 2 \
	    -c $top_srcdir/tests/confs/one-ip \
	    -l $top_srcdir/tests/leases/one-ip -o tests/outputs/$IAM
diff -u $top_srcdir/tests/expected/$IAM tests/outputs/$IAM
exit $?
