#!/bin/sh
#
# Minimal regression test suite.

IAM=$(basename $0)
TESTDATA=${IAM%-*}

if [ ! -d tests/outputs ]; then
	mkdir tests/outputs
fi

dhcpd-pools -c $top_srcdir/tests/confs/$TESTDATA \
	    -l $top_srcdir/tests/leases/$TESTDATA -o tests/outputs/$IAM \
	    --warning 80 --perfdata
diff -u $top_srcdir/tests/expected/$IAM tests/outputs/$IAM
exit $?
